<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FonctionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('fonctions');

        $directions = array(
            array('libelle' => 'SECRETAIRE GENERAL','direction_id' => 2),
            array('libelle' => 'SECRETAIRE GENERAL ADJOINT','direction_id' => 2),
            array('libelle' => 'CHEF DE SCE. SUIVI ET EVALUATION','direction_id' => 2),
            array('libelle' => 'CHEF DU SERVICE COURRIER','direction_id' => 2),
            array('libelle' => 'ASSISTANTE DE SECURITE','direction_id' => 2),
            array('libelle' => 'AGENT DE GESTION ADMINISTRATIVE','direction_id' => 2),
            array('libelle' => 'ASSISTANTE DE DIRECTION','direction_id' => 2),
            array('libelle' => 'SECRETAIRE BUREAUTIQUE-SECRETAIRE DU SECRETAIRE GENERAL','direction_id' => 2),
            array('libelle' => 'SECRETAIRE BUREAUTIQUE -SECRETAIRE DU SECRETAIRE GENERAL ADJOINT','direction_id' => 2),
            array('libelle' => 'SECRETAIRE BUREAUTIQUE','direction_id' => 2),
            array('libelle' => 'AGENT DE BUREAU','direction_id' => 2),
            array('libelle' => 'CHAUFFEUR DU SG','direction_id' => 2),
            array('libelle' => 'CHAUFFEUR DU SGA','direction_id' => 2),
            array('libelle' => 'CHAUFFEUR DE POOL','direction_id' => 2),
            array('libelle' => 'SOUS-DIRECTEUR SECURITE','direction_id' => 2),
            array('libelle' => 'CHEF DE SERVICE OPERATIONS ET INTERVENTIONS','direction_id' => 2),
            array('libelle' => 'CHEF DE SERVICE SECURITE URBAINE-COMMANDANT LA POLICE MUNICIPALE','direction_id' => 2),
            array('libelle' => 'POLICIER MUNICIPAL','direction_id' => 2),

            array('libelle' => 'DIRECTEUR DE CABINET ','direction_id' => 1),
            array('libelle' => 'CONSEILLER TECHNIQUE DU MAIRE','direction_id' => 1),
            array('libelle' => 'CHEF DE SERVICE COMMUNICATION DU MAIRE','direction_id' => 1),
            array('libelle' => 'CHEF DE SERVICE SECURITE ','direction_id' => 1),
            array('libelle' => 'CHEF DU SERVICE PROTOCOLE','direction_id' => 1),
            array('libelle' => 'CHEF DE SERVICE PROJETS','direction_id' => 1),
            array('libelle' => 'RESPONSABLE LOGISTIQUE','direction_id' => 1),
            array('libelle' => 'SECRETAIRE PARTICULIERE DU MAIRE','direction_id' => 1),
            array('libelle' => 'SECRETAIRE DU DIRECTEUR DE CABINET','direction_id' => 1),
            array('libelle' => 'SECRETAIRE DES MAIRES-ADJOINTS','direction_id' => 1),
            array('libelle' => 'SECRETAIRE BUREAUTIQUE','direction_id' => 1),
            array('libelle' => 'AGENT DE GESTION ADMINISTRATIVE','direction_id' => 1),
            array('libelle' => 'AGENT DE SECURITE','direction_id' => 1),
            array('libelle' => 'AGENT DU PROTOCOLE','direction_id' => 1),
            array('libelle' => 'CHAUFFEUR DU MAIRE','direction_id' => 1),
            array('libelle' => 'CHAUFFEUR DU DIR. CAB.','direction_id' => 1),
            array('libelle' => 'CHAUFFEUR DE POOL','direction_id' => 1),
            array('libelle' => 'ATTACHE DE CABINET','direction_id' => 1),

            array('libelle' => 'DIRECTEUR DES SERVICES ADMINISTRATIFS ','direction_id' => 3),
            array('libelle' => 'ASSISTANT DU DIRECTEUR/CHEF DE SERVICE CONCEPTION ET REDACTION ADMINISTRATIVE','direction_id' => 3),
            array('libelle' => 'CONSEILLER D’EDUCATION PERMANENTE','direction_id' => 3),
            array('libelle' => 'AGENTS DES FINANCES','direction_id' => 3),
            array('libelle' => 'AGENT DE GESTION ADMINISTRATIVE ','direction_id' => 3),
            array('libelle' => 'CHAUFFEUR DU DSA','direction_id' => 3),
            array('libelle' => 'CHAUFFEUR DE POOL','direction_id' => 3),
            array('libelle' => 'CHEF SERVICE DU SERVICE QUALITE','direction_id' => 3),
            array('libelle' => 'SECRETAIRE DE DIRECTION','direction_id' => 3),
            array('libelle' => 'ATTACHE DE COMMUNICATION','direction_id' => 3),
            array('libelle' => 'TECHNICIEN SUPERIEUR EN COMMUNICATION','direction_id' => 3),
            array('libelle' => 'ASSISTANTE QUALITE','direction_id' => 3),
            array('libelle' => 'S/D DES RESOURCES HUMAINES','direction_id' => 3),
            array('libelle' => 'CHEF DE SERVICE GESTION ADMINISTRATIVE DU PERSONNEL ET DES AFFAIRES SOCIALES','direction_id' => 3),
            array('libelle' => 'CHEF DE SERVICE GESTION PREVISIONNEL DES EMPLOIS, DES COMPETENCES ET DE LA FORMATION','direction_id' => 3),
            array('libelle' => 'S/D ETAT-CIVIL ET POPULATION STATISTIQUES','direction_id' => 3),
            array('libelle' => 'CHEF DE SERVICE ETAT-CIVIL ET MARIAGE','direction_id' => 3),
            array('libelle' => 'CHEF DE SERVICE DES ARCHIVES ET DE DOCUMENTATION','direction_id' => 3),
            array('libelle' => 'CHEF DU SERVICE POPULATION/STATISTIQUES','direction_id' => 3),
            array('libelle' => 'CHEF DU BUREAU DECES','direction_id' => 3),
            array('libelle' => 'CHEF DE BUREAU NAISSANCE','direction_id' => 3),
            array('libelle' => 'CHEF BUREAU MARIAGE','direction_id' => 3),
            array('libelle' => 'ASSISTANTE MARIAGE','direction_id' => 3),
            array('libelle' => 'ARCHIVISTE','direction_id' => 3),
            array('libelle' => 'AGENT TRANSCRIPTEUR','direction_id' => 3),
            array('libelle' => 'SOUS-DIRECTEUR DES AFFAIRES ADMINISTRATIVES','direction_id' => 3),
            array('libelle' => 'CHEF DU SERVICE RECENSEMENT MILITAIRE','direction_id' => 3),
            array('libelle' => 'AGENT DES TECH. STATS','direction_id' => 3),
            array('libelle' => 'CHEF DU SERVICE LEGISLATION','direction_id' => 3),
            array('libelle' => 'AGENT DU BUREAU MILIITAIRE','direction_id' => 3),
            array('libelle' => 'SOUS-DIRECTEUR INFORMATIQUE','direction_id' => 3),
            array('libelle' => 'CHEF DU SERVICE GESTION DU PARC INFORMATIQUE','direction_id' => 3),
            array('libelle' => 'INFORMATICIEN MAINTENANCIER','direction_id' => 3),
            array('libelle' => 'CHEF DU SERVICE RENFORCEMENT DES CAPACITES  EN INFORMATIQUE ET SECURISATION DES ACTES D’ETAT-CIVIL','direction_id' => 3),
            array('libelle' => 'CHEF DU SERVICE ETUDES ET PROJETS INFORMATIQUES','direction_id' => 3),
            array('libelle' => 'OPERATRICE DE SAISIE','direction_id' => 3),
            array('libelle' => 'TECHNICIEN MAINTENANCIER','direction_id' => 3),
            array('libelle' => 'TECHNICIEN RESEAUX INFORMATIQUES','direction_id' => 3),
            array('libelle' => 'TECHNICIEN SUPERIEUR RESEAU ET LOGICIEL INFORMATIQUE','direction_id' => 3),
            array('libelle' => 'AGENT DE GESTION ADMINISTRATIF','direction_id' => 3),
            array('libelle' => 'S/D ETUDES ET PROJETS ADMINISTRATIFS','direction_id' => 3),
            array('libelle' => 'CHEF DE SERVICE PLANIFICATION','direction_id' => 3),
            array('libelle' => 'SOUS-DIRECTRICE AFFAIRES JURIDIQUES ','direction_id' => 3),
            array('libelle' => 'CHEF DU SERVICE CONTENTIEUX','direction_id' => 3),
            array('libelle' => 'AGENT DE BUREAU','direction_id' => 3),
            array('libelle' => 'SECRETAIRE BUREAUTIQUE','direction_id' => 3),
            array('libelle' => 'REDACTEUR','direction_id' => 3),
            array('libelle' => 'REDACTEUR PRINCIPAL','direction_id' => 3),
            array('libelle' => 'AGENT D’ACCUEIL DE L’ETAT-CIVIL','direction_id' => 3),
            array('libelle' => 'CHAUFFEUR','direction_id' => 3),

            array('libelle' => 'DIRECTEUR DES SERVICES FINANCIERS','direction_id' => 8),
            array('libelle' => 'SECRETAIRE DE DIRECTION','direction_id' => 8),
            array('libelle' => 'SECRETAIRE COMPTABLE','direction_id' => 8),
            array('libelle' => 'SOUS-DIRECTEUR DE LA COMPTABILITE ET DU CONTROLE DEPENSES PREALABLES','direction_id' => 8),
            array('libelle' => 'CHEF DE SERVICE SALAIRES CHARGES SOCIALES ET ABONNEMENT','direction_id' => 8),
            array('libelle' => 'CHEF SERVICE COMPTABILITE','direction_id' => 8),
            array('libelle' => 'REGISSEUR DES RECETTES','direction_id' => 8),
            array('libelle' => 'COMPTABLE MATIERE','direction_id' => 8),
            array('libelle' => 'COMPTABLE- GESTIONNAIRE BASES DE DONNEES','direction_id' => 8),
            array('libelle' => 'COMPTABLE','direction_id' => 8),
            array('libelle' => 'CHEF SERVICE INVESTISSEMENT','direction_id' => 8),
            array('libelle' => 'AIDE COMPTABLE','direction_id' => 8),
            array('libelle' => 'SECRETAIRE ASSISTANTE COMPTABLE','direction_id' => 8),
            array('libelle' => 'SOUS-DIRECTEUR AFFAIRES ECONOMIQUES','direction_id' => 8),
            array('libelle' => 'CHEF DE SERVICE ECONOMIQUE','direction_id' => 8),
            array('libelle' => 'SOUS-DIRECTEUR AUDIT ET CONTROLE','direction_id' => 8),
            array('libelle' => 'SOUS DIRECTEUR DES RECETTES PROPRES','direction_id' => 8),
            array('libelle' => 'SOUS DIRECTEUR DES  RECETTES SPECIFIQUES','direction_id' => 8),
            array('libelle' => 'SOUS-DIRECTRICE DES IMPOTS D’ETAT ','direction_id' => 8),
            array('libelle' => 'CHEF DE SERVICE MARCHE PUBLIC','direction_id' => 8),
            array('libelle' => 'CHEF SERVICE PUBLICITE','direction_id' => 8),
            array('libelle' => 'CHEF SERVICE TRANSPORT','direction_id' => 8),
            array('libelle' => 'GESTIONNAIRE MARCHE ANNEXE-VRIDI','direction_id' => 8),
            array('libelle' => 'GESTIONNAIRE DE MARCHE CENTRAL PORT BOUET CENTRE','direction_id' => 8),
            array('libelle' => 'GESTIONNAIRE DE MARCHE ANNEXES DE JEAN FOLLY–ADJOUFFOU','direction_id' => 8),
            array('libelle' => 'GESTIONNAIRE MARCHE IRHO','direction_id' => 8),
            array('libelle' => 'AGENT DU DOMAINE','direction_id' => 8),
            array('libelle' => 'CONTROLEUR DE TAXES','direction_id' => 8),
            array('libelle' => 'CAISSIERE','direction_id' => 8),
            array('libelle' => 'OPERATRICE DE SAISIE','direction_id' => 8),
            array('libelle' => 'AGENT DE RECOUVREMENT (CS VRIDI CITE)','direction_id' => 8),
            array('libelle' => 'AGENT DE RECOUVREMENT','direction_id' => 8),
            array('libelle' => 'CHAUFFEUR','direction_id' => 8),
            array('libelle' => 'CHEF DU SERVICE DOMANIAL','direction_id' => 8),
            array('libelle' => 'AGENT DE DOMAINE','direction_id' => 8),
            array('libelle' => 'CHEF SERVICE INFORMATIQUE  (VRIDI CITE)','direction_id' => 8),
            array('libelle' => 'SECRETAIRE DE DIRECTION (VRIDI CITE)','direction_id' => 8),
            array('libelle' => 'AGENT DE BUREAU','direction_id' => 8),
            array('libelle' => 'CHAUFFEUR (VRIDI CITE)','direction_id' => 8),
            array('libelle' => 'INFORMATICIEN MAINTENANCIER','direction_id' => 8),
            array('libelle' => 'SECRETAIRE COMPTABLE (VRIDI)','direction_id' => 8),
            array('libelle' => 'CONTROLEUR DE TAXES (VRIDI)','direction_id' => 8),

            array('libelle' => 'DIERCTEUR DES SERVICES TECHNICQUES ET MOYENS GENERAUX','direction_id' => 7),
            array('libelle' => 'SOUS-DIRECTRICE DU DOMAINE DU PATRIMOINE ET DES EQUIPEMENTS','direction_id' => 7),
            array('libelle' => 'SOUS-DIRECTEUR DE LA PLANIFICATION ET DES ETUDES PROSPECTIVES','direction_id' => 7),
            array('libelle' => 'S/D EN CHARGE DU GRAND MENAGE ET DU DEVELOPPEMENT DURABLE ','direction_id' => 7),
            array('libelle' => 'CHEF DU SCE.PARC AUTOMOBILE','direction_id' => 7),
            array('libelle' => 'CHEF DU SCE.MAINTENANCE','direction_id' => 7),
            array('libelle' => 'CHEF DE SERVICE VOIRIE RESEAUX DIVERS','direction_id' => 7),
            array('libelle' => 'S/D EN CHARGE DU GRAND MENAGE ET DU DEVELOPPEMENT DURABLE ','direction_id' => 7),
            array('libelle' => 'CHEF DU SCE.PARC AUTOMOBILE','direction_id' => 7),
            array('libelle' => 'CHEF DU SCE.MAINTENANCE','direction_id' => 7),
            array('libelle' => 'CHEF DE SERVICE VOIRIE RESEAUX DIVERS','direction_id' => 7),
            array('libelle' => 'AGENT DE GESTION ADMINISTRATIVE','direction_id' => 7),
            array('libelle' => 'RESPONSABLE SUIVI DES TRAVAUX','direction_id' => 7),
            array('libelle' => 'CHEF SERVICE CONSTRUCTION ET URBANISME','direction_id' => 7),
            array('libelle' => 'TECHNICIEN DES TRAVAUX PUBLICS','direction_id' => 7),
            array('libelle' => 'LOGISTICIEN','direction_id' => 7),
            array('libelle' => 'CHEF SECTION EQUIPEMENT','direction_id' => 7),
            array('libelle' => 'SECRETAIRE BUREAUTIQUE','direction_id' => 7),
            array('libelle' => 'SECRETAIRE DE DIRECTION','direction_id' => 7),
            array('libelle' => 'MENUISIER','direction_id' => 7),
            array('libelle' => 'MAÇON','direction_id' => 7),
            array('libelle' => 'INFORMATICIEN MAINTENANCIER','direction_id' => 7),
            array('libelle' => 'RESPONSABLE SUIVI DES TRAVAUX','direction_id' => 7),
            array('libelle' => 'AGENT TECHNIQUE','direction_id' => 7),
            array('libelle' => 'ASSISTANT COMPTABLE','direction_id' => 7),
            array('libelle' => 'AGENT DE BUREAU','direction_id' => 7),
            array('libelle' => 'AGENT TECHNIQUE (PLOMBIER)','direction_id' => 7),
            array('libelle' => 'AGENT TECHNIQUE (ELECTRICIEN)','direction_id' => 7),
            array('libelle' => 'CHEF DE SERVICE DU GARAGE MUNICIPAL','direction_id' => 7),
            array('libelle' => 'ASSISTANTE DE DIRECTION','direction_id' => 7),
            array('libelle' => 'SOUS-DIRECTEUR  ASSAINISSEMENT','direction_id' => 7),
            array('libelle' => 'CHEF DE SERVICE SALUBRITE ET CADRE DE VIE','direction_id' => 7),
            array('libelle' => 'CHEF D’EQUIPE','direction_id' => 7),
            array('libelle' => 'CHAUFFEUR DU CAR','direction_id' => 7),
            array('libelle' => 'CHAUFFEUR DU MINI CAR','direction_id' => 7),
            array('libelle' => 'CHAUFFEUR','direction_id' => 7),
            array('libelle' => 'CHAUFFEUR DE POOL','direction_id' => 7),
            array('libelle' => 'CHAUFFEUR DU DIRECTEUR DES SERVICES TECHNIQUES ET MOYENS GENERAUX','direction_id' => 7),
            array('libelle' => 'MACHINISTE (CONDUCTEUR D’ENGINS)','direction_id' => 7),
            array('libelle' => 'CONDUCTEUR DE TRAVAUX','direction_id' => 7),
            array('libelle' => 'CHEF DU SCE.ENVIRONNEMENT ET CADRE DE VIE','direction_id' => 7),
            array('libelle' => 'AGENT TECHNIQUE','direction_id' => 7),
            array('libelle' => 'TECHNICIEN SUPERIEUR EN ENVIRONNEMENT','direction_id' => 7),
            array('libelle' => 'CHEF D’EQUIPE SALUBRITE PUBLIQUE','direction_id' => 7),
            array('libelle' => 'MANŒUVRE (CS AKO BRAKRE)','direction_id' => 7),
            array('libelle' => 'TECHNICIENNE DE SURFACE','direction_id' => 7),

            array('libelle' => 'EDUCATRICE PRESCOLAIRE ADJOINTE','direction_id' => 5),
            array('libelle' => 'EDUCATRICE PRESCOLAIRE ','direction_id' => 5),
            array('libelle' => 'FEMME DE CHARGE','direction_id' => 5),
            array('libelle' => 'EDUCATRICE PRESCOLAIRE ADJOINTE  (CPPE)','direction_id' => 5),
            array('libelle' => 'AIDE MATERNELLE (CPPE)','direction_id' => 5),
            array('libelle' => 'AGENT ADMINISTRATIF','direction_id' => 5),
            array('libelle' => 'AGENT DE BUREAU','direction_id' => 5),
            array('libelle' => 'GARDIEN','direction_id' => 5),
            array('libelle' => 'SOU-DIRECTEUR EDUCATION VIE ASSOCIATIVE ET INSERTION','direction_id' => 5),
            array('libelle' => 'SOUS-DIRECTRICE COOPERATION ET RELATIONS DE PARTENARIAT','direction_id' => 5),
            array('libelle' => 'CHEF DU SERVICE SPORT ET LOISIRS','direction_id' => 5),
            array('libelle' => 'Chargé de Communication','direction_id' => 5),
            array('libelle' => 'CHEF DU SERVICE APPRENTISSAGE ET INSERTION','direction_id' => 5),
            array('libelle' => 'ANIMATEUR CULTUREL','direction_id' => 5),
            array('libelle' => 'CHEF DU SERVICE ANIMATIONS CULTURELLES','direction_id' => 5),
            array('libelle' => 'CHEF DU SERVICE VIE ASSOCIATIVE ET PROMOTION DU GENRE','direction_id' => 5),
            array('libelle' => 'CONSEILLER D’ACTION CULTURELLE','direction_id' => 5),
            array('libelle' => 'CHEF SECTION ANIMATION CULTURELLE','direction_id' => 5),
            array('libelle' => 'SECRETAIRE BUREAUTIQUE/SECRETAIRE DU DIR.DASCPH','direction_id' => 5),
            array('libelle' => 'CHEF DU SERVICE EDUCATION ET ALPHABETISATION','direction_id' => 5),
            array('libelle' => 'REDACTEUR','direction_id' => 5),
            array('libelle' => 'EDUCATEUR','direction_id' => 5),
            array('libelle' => 'AGENT DE GESTION ADMINISTRATIVE','direction_id' => 5),
            array('libelle' => 'CHEF DE SERVICE PROJETS','direction_id' => 5),
            array('libelle' => 'OPERATRICE DE SAISIE','direction_id' => 5),
            array('libelle' => 'SOUS-DIRECTRICE  BIBLIOTHEQUE MUNICIPALE','direction_id' => 5),
            array('libelle' => 'BIBLIOTHECAIRE ','direction_id' => 5),
            array('libelle' => 'AIDE BIBLIOTHECAIRE','direction_id' => 5),
            array('libelle' => 'SECRETAIRE BUREAUTIQUE','direction_id' => 5),
            array('libelle' => 'INSPECTEUR D’EDUCATION','direction_id' => 5),
            array('libelle' => 'BIBLIOTHECAIRE','direction_id' => 5),
            array('libelle' => 'CHEF DE SERVICE MAISON D’ACCUEIL D’HERBERGEMENT ET DE FORMATION','direction_id' => 5),
            array('libelle' => 'RECEPTIONNISTE ADJOINT','direction_id' => 5),
            array('libelle' => 'AIDE SOCIALE','direction_id' => 5),

            array('libelle' => 'CHEF SECTION INSPECTION SANITAIRE','direction_id' => 4),
            array('libelle' => 'CHEF DE GROUPE','direction_id' => 4),
            array('libelle' => 'ANIMATEUR D’EDUCATION SANITAIRE','direction_id' => 4),
            array('libelle' => 'CHEF DE SECTION INSPECTION SANITAIRE','direction_id' => 4),
            array('libelle' => 'DIRECTRICE DES SERVICES SANITAIRE H.P','direction_id' => 4),
            array('libelle' => 'SOUS-DIRECTEUR DES SERVICES SANITAIRES ','direction_id' => 4),
            array('libelle' => 'SOUS-DIRECTRICE HYGIENE PUBLIQUE ','direction_id' => 4),
            array('libelle' => 'AGENT D’HYGIENE','direction_id' => 4),
            array('libelle' => 'CHEF DE SERVICE CONCEDES ET POMPES FUNEBRES','direction_id' => 4),
            array('libelle' => 'CHEF DE SERVICEHYGIENE PUBLIQUE','direction_id' => 4),
            array('libelle' => 'CHEF DE SECTION EN CHARGE DU LABORATOIRE DU CEDV','direction_id' => 4),
            array('libelle' => 'CHAUFFEUR DE LA DIRECTRICE','direction_id' => 4),
            array('libelle' => 'CHEF DU SERVICE DU CENTRE D’ECOUTE ET DE DEPISTAGE (CEDV)','direction_id' => 4),
            array('libelle' => 'INFIRMIER DIPLOME D’ETAT (CEDV)','direction_id' => 4),
            array('libelle' => 'SECRETAIRE MEDICAL','direction_id' => 4),
            array('libelle' => 'CHEF DU SERVICE EN CHARGE DE L’HOPITAL MUNICIPA','direction_id' => 4),
            array('libelle' => 'GESTIONNAIRE DU CENTRE DE SANTE ','direction_id' => 4),
            array('libelle' => 'AGENT DE SANTE','direction_id' => 4),
            array('libelle' => 'ANIMATRICE D’EDUCATION SANITAIRE','direction_id' => 4),
            array('libelle' => 'AIDE SOIGNANTE','direction_id' => 4),
            array('libelle' => 'CAISSIERE','direction_id' => 4),
            array('libelle' => 'AGENT DE BUREAU','direction_id' => 4),
            array('libelle' => 'AGENT DE RECOUVREMENT ','direction_id' => 4),
            array('libelle' => 'SOUS-DIRECTRICE AFF.SOCIALE ','direction_id' => 4),
            array('libelle' => 'CHEF SERVICE ACTIVITES COMMUNAUTAIRES','direction_id' => 4),
            array('libelle' => 'CHEF DE SERVICE D’ASSISTANCE SOCIALE','direction_id' => 4),
            array('libelle' => 'ASSISTANTE SOCIALE','direction_id' => 4),

            array('libelle' => 'DIRECTEUR COMMUNICATION','direction_id' => 6),
            array('libelle' => 'CHEF SERVICE RELATIONS PUBLIQUES','direction_id' => 6),
            array('libelle' => 'SECRETAIRE DU DIRECTEUR COMMUNICATION','direction_id' => 6),
            array('libelle' => 'SOUS-DIRECTRICE  RADIO DIFFUSION','direction_id' => 6),
            array('libelle' => 'CHEF DU SERVICE PRESSE ECRITE','direction_id' => 6),
            array('libelle' => 'REDACTEUR  CORRECTEUR','direction_id' => 6),
            array('libelle' => 'AGENT AUDIOVISUEL ET PRESSE EN LIGNE','direction_id' => 6),
            array('libelle' => 'CHEF SECTION PRESSE ECRITE','direction_id' => 6),
            array('libelle' => 'CHEF SERVICE INFORMATION RADIO','direction_id' => 6),
            array('libelle' => 'CHEF SERVICE PHOTOGRAPHIES ET ARCHIVES','direction_id' => 6),
            array('libelle' => 'CHEF SERVICE COMMERCIALE','direction_id' => 6),
            array('libelle' => 'CHEF SCE.PRESSE EN LIGNE','direction_id' => 6),
            array('libelle' => 'CHEF DE SERVICE MAINTENANCE','direction_id' => 6),
            array('libelle' => 'CHEF SECTION TECHNIQUE','direction_id' => 6),
            array('libelle' => 'TECHNICIEN RADIO','direction_id' => 6),
            array('libelle' => 'TECHNICIEN','direction_id' => 6),
            array('libelle' => 'CHEF SERVICE AUDIOVISUEL','direction_id' => 6),
            array('libelle' => 'ASSISTANTE DE PRODUCTION RADIO','direction_id' => 6),
            array('libelle' => 'ANIMATEUR RADIO','direction_id' => 6),
            array('libelle' => 'CHEF de SERVICE PROGRAMMATION','direction_id' => 6),
            array('libelle' => 'AGENT DE BUREAU','direction_id' => 6),
            array('libelle' => 'SOUS-DIRECTEUR  PRESSE ET COMMUNICATION EVENE MENTIELLE','direction_id' => 6),
            array('libelle' => 'ANIMATEUR RESEAU','direction_id' => 6),
            array('libelle' => 'ASSISTANTE EN COMMUNICATION','direction_id' => 6),
            array('libelle' => 'CHEF DU SERVICE MARKETING','direction_id' => 6),
            array('libelle' => 'SOUS-DIRECTEUR MARKETING ET PUBLICITE','direction_id' => 6),
            array('libelle' => 'TECHNICIEN SUPERIEUR DE COMMUNICATION','direction_id' => 6),

            array('libelle' => 'CABINET','direction_id' => 6),
            array('libelle' => 'CABINET','direction_id' => 6),

        );

        DB::table('fonctions')->insert($directions);
    }
}
