on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
name: 🚀 Deploy app on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:

    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 22.2.0
      uses: actions/setup-node@v2
      with:
        node-version: '22.2.0'

    - name: Configure PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: 🔨 Build Project
      run: |
        composer install --no-dev --optimize-autoloader

    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.monwebmaster.net
        username: mystock@mystock.monwebmaster.net
        password: cxILI]fLC,gD
        protocol: ftp
        port: 21
        exclude: |
          **/.git*
          **/.git*/**
          **/.git*/**
          **/node_modules/**
          **/vendor/**
    - name: 🔨 Clear cache
      run: |
        php artisan optimize:clear
